Try SNMP first and if that fails try aruba_command (ssh)

diff --git a/aruba_model b/aruba_model
--- a/aruba_model
+++ b/aruba_model
@@ -9,6 +9,14 @@ if [ -z "$SWITCH" ]; then
 	return 1 2>&- || exit
 fi
 
-. aruba_auth
+SNMP_RO_COMMUNITY="public"
+[ -n $(command -v pktools_vars) ] && . pktools_vars
 
-aruba_command $SWITCH "getmib 1.3.6.1.2.1.1.1.0" | grep -Pv '^\s*$' | sed -E 's/^[^=]+ *= *//'
+MODEL=$(timeout 1 snmpget -v2c -c$SNMP_RO_COMMUNITY 10.95.64.11 1.3.6.1.2.1.1.1.0 -Oe 2>&- | sed -E 's/.*STRING: //')
+if [ -z "$MODEL" ]; then
+	. aruba_auth
+	MODEL=$(aruba_command $SWITCH "getmib 1.3.6.1.2.1.1.1.0" | grep -Pv '^\s*$' | sed -E 's/^[^=]+ *= *//')
+fi
+
+echo -n "$SWITCH: "
+[ -n "$MODEL" ] && echo "$MODEL" || echo "Could not determine model"
