Process multiple switches given via command arguments and/or STDIN

diff --git a/aruba_model b/aruba_model
--- a/aruba_model
+++ b/aruba_model
@@ -1,22 +1,40 @@
 #!/usr/bin/env bash
 
-SWITCH=$1
+SNMP_TIMEOUT=2
+SCRIPT="$(basename "$0")"
 
-if [ -z "$SWITCH" ]; then
-	echo "aruba_model returns the model of the switch. Usage:"
-	echo "aruba_model switch_ip"
-	echo "aruba_model 192.168.3.12"
-	return 1 2>&- || exit
-fi
+function help() {
+	cat <<-EOF
+
+		$SCRIPT switch_ips$_description_of_functionality_
+	
+		Usage example:
+		  $SCRIPT returns the model of the switch. Usage:
+		  $SCRIPT 192.168.3.11 192.168.3.12
+
+	EOF
+	return 1 2>&- || exit 1
+}
+
+grep -Piq -- '--help|-h' <<< $* && help
+
+PARAMS=$*
+[ ! -t 0 ] && PARAMS="$(cat | tr '\n' ' ' | tr '\r' ' ') $PARAMS"
+[ -z "$PARAMS" ] && help
 
 SNMP_RO_COMMUNITY="public"
 [ -n $(command -v pktools_vars) ] && . pktools_vars
 
-MODEL=$(timeout 1 snmpget -v2c -c$SNMP_RO_COMMUNITY 10.95.64.11 1.3.6.1.2.1.1.1.0 -Oe 2>&- | sed -E 's/.*STRING: //')
-if [ -z "$MODEL" ]; then
-	. aruba_auth
-	MODEL=$(aruba_command $SWITCH "getmib 1.3.6.1.2.1.1.1.0" | grep -Pv '^\s*$' | sed -E 's/^[^=]+ *= *//')
-fi
+for SWITCH in $PARAMS; do
+	SWITCH=$(ip_validate $SWITCH)
+	[ -z "$SWITCH" ] && echo "$SWITCH: Invalid IP address" >&2 && help
 
-echo -n "$SWITCH: "
-[ -n "$MODEL" ] && echo "$MODEL" || echo "Could not determine model"
+	MODEL=$(timeout $SNMP_TIMEOUT snmpget -v2c -c$SNMP_RO_COMMUNITY $SWITCH 1.3.6.1.2.1.1.1.0 -Oe 2>&- | sed -E 's/.*STRING: //')
+	if [ -z "$MODEL" ]; then
+		. aruba_auth
+		MODEL=$(aruba_command $SWITCH "getmib 1.3.6.1.2.1.1.1.0" | grep -Pv '^\s*$' | sed -E 's/^[^=]+ *= *//')
+	fi
+
+	echo -n "$SWITCH: "
+	[ -n "$MODEL" ] && echo "$MODEL" || echo "Could not determine model"
+done
