Added some fixes and pmprovements

diff --git a/cisco_packet_capture b/cisco_packet_capture
--- a/cisco_packet_capture
+++ b/cisco_packet_capture
@@ -7,17 +7,46 @@ CISCO_ROUTER="$1"
 
 DIRTY=""
 
+function exitTrap {
+	emergencyStop 2>&- &
+	echo -n "${NC}"
+	unset ACL_DST_IP
+	unset ACL_DST_WILDCARD
+	unset ACL_SRC_IP
+	unset ACL_SRC_WILDCARD
+	unset CISCO_ROUTER
+	unset DIRTY
+	unset INT_COMMAND
+	unset INTERFACE
+	unset INTERFACE_LIST
+	unset INTERFACES
+	unset PCAP_FILE
+	unset TEMPLATE_ACL
+	unset TEMPLATE_REMOVE_BUFFER
+	unset TEMPLATE_STOP
+	unset TFTP_GET_COMMAND
+	unset TFTP_SERVER
+}
+
+trap exitTrap EXIT
+
 source colors.sh
+
+if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+	echo "${RED}You can't source this file. If you want to pre-cache cisco passwords, run . cisco_command first.${NC}"
+	return 1
+fi
+
 
 function ip_validate {
 	[[ "$1" =~ ^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$ ]] || exit 1
 	echo "$1"
 }
 
-ACL_SRC_IP=0.0.0.0
-ACL_SRC_WILDCARD=255.255.255.255
-ACL_DST_IP=0.0.0.0
-ACL_DST_WILDCARD=255.255.255.255
+#ACL_SRC_IP=0.0.0.0
+#ACL_SRC_WILDCARD=255.255.255.255
+#ACL_DST_IP=0.0.0.0
+#ACL_DST_WILDCARD=255.255.255.255
 
 while [ -z "$CISCO_ROUTER" ]; do
 	echo -n "Enter hostname/IP of the cisco router: "
@@ -49,7 +78,8 @@ done
 if [ -z "$CISCO_SHOWRUNN_PASS" ]; then
 	if [ ! -t 1 ] || [ ! -t 0 ]; then
 		# stdout isn't a terminal
-		echo "There are no cached credentials. Please run '. cisco_command' alone to cache them."
+		echo "${RED}There are no cached credentials. Please exit this and run '. cisco_command' alone to pre-cache them."
+		echo "Or enter them below for this session only${NC}"
 		return 2>&-
 		exit 1
 	fi
@@ -71,15 +101,16 @@ export ENABLE="$CISCO_SHOWRUNN_ENABLE"
 
 INT_COMMAND="show ip interface brief"
 INTERFACE_LIST="$(. cisco_command $CISCO_ROUTER $INT_COMMAND | grep -Pv """$INT_COMMAND|NVI0|Embedded-Service-Engine""")"
-INTERFACES=$(echo "$INTERFACE_LIST" | grep -Pv 'IP-Address' | awk '{print $1}')
+INTERFACES=$(echo "$INTERFACE_LIST" | grep -Pv 'IP-Address' | awk '{print $1}' | tr '\n' ' ')
 
 echo "$INTERFACE_LIST"
 echo
 echo "Select capture interface: "
-
-select INTERFACE in $INTERFACES; do
+echo -n "${BLUE}"
+select INTERFACE in $(echo $INTERFACES); do
 	[ -n "$INTERFACE" ] && break
 done
+echo -n "${NC}"
 
 TEMPLATE_ACL="
 permit ip $ACL_SRC_IP $ACL_SRC_WILDCARD $ACL_DST_IP $ACL_DST_WILDCARD
@@ -129,8 +160,9 @@ function startCapture {
 
 function statusWait {
 	while ! read -t 1; do
+		echo -n "${GREEN}"
 		echo "$TEMPLATE_STATUS" | . cisco_command "$CISCO_ROUTER"
-		echo "${GREEN}Capturing. Press ENTER to stop.${NC}"
+		echo "${LGREEN}Capturing. Press ENTER to stop.${NC}"
 		sleep 1
 	done
 }
@@ -138,7 +170,7 @@ function statusWait {
 function stopCapture {
 	echo "${RED}Stopping capture${NC}"
 	echo "$TEMPLATE_STOP" | . cisco_command "$CISCO_ROUTER"
-	echo "${GREEN}Transferring capture file $PCAP_FILE to tftp server $TFTP_SERVER${NC}"
+	echo "${GREEN}Transferring capture file $PCAP_FILE to tftp server $TFTP_SERVER"
 	echo "$TEMPLATE_TRANSFER" | . cisco_command "$CISCO_ROUTER"
 }
 
@@ -153,21 +185,16 @@ function openWireshark {
 
 function emergencyStop {
 	if [ -n "$DIRTY" ]; then
-		echo "${RED}Attempting Emergency cleanup in the backgroud.${NC}"
+		echo "${RED}Attempting Emergency cleanup in the backgroud.${LRED}"
 	 	echo "$TEMPLATE_EMERGENCY_STOP" | . cisco_command "$CISCO_ROUTER"
-		echo "${GREEN}Completed. Check output in blue for problems during cleanup.${NC}"
+		echo "${GREEN}Completed. Check output in light red for problems during cleanup.${NC}"
 	fi
-}
-
-function exitTrap {
-	emergencyStop &
 }
 
 
 # Let the EXIT trap know that we will need to clean up the router
 DIRTY=true
 
-trap exitTrap EXIT
 
 # Start the capture
 startCapture
@@ -183,4 +210,4 @@ DIRTY=""
 
 getFile
 openWireshark
-echo "${GREEN}Capture completed{NC}"
+echo "${GREEN}Capture completed${NC}"
