Added nocolor and search

diff --git a/cisco_known_mac_vendor_search b/cisco_known_mac_vendor_search
--- a/cisco_known_mac_vendor_search
+++ b/cisco_known_mac_vendor_search
@@ -9,8 +9,40 @@ function finish {
 }
 trap finish EXIT
 
+function usage {
+	echo "Usage: $0 host [search pattern] [-n|--nocolor]" >&2
+	exit 1
+}
+
+PARAMS=""
+while (( "$#" )); do
+  case "$1" in
+    -n|--nocolor)
+      NOCOLOR="yes"
+      shift 1
+      ;;
+    --) # end argument parsing
+      shift
+      break
+      ;;
+    -*|--*=) # unsupported flags
+      echo "Error: Unsupported flag $1" >&2
+			usage
+      ;;
+    *) # preserve positional arguments
+      PARAMS="$PARAMS $1"
+      shift
+      ;;
+  esac
+done
+# set positional arguments in their proper place
+eval set -- "$PARAMS"
+
 NODE=$1
-[ -z "$NODE" ] && echo "Usage: $0 host" && exit 1
+[ -z "$NODE" ] && usage
+
+shift
+SEARCH="$*"
 
 function refreshDatabase() {
 	OLD=$(find $DB -type f -mtime +7 2>&- | wc -l)
@@ -26,17 +58,26 @@ function findVendor() {
 	grep -iP "^$OUI" "$DB" | cut -d, -f3- | tr -d '"' | sed -E 's/,(\S)/, \1/g;s/,[^,]+,[^,]+,[^,]+,[^,]+$//g'
 }
 
+function getData() {
+	while IFS= read -r LINE; do
+		IP_MAC=$(sed -E 's/.*\.([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) "(..) (..) (..) (..) (..) (..) ?"/\1 \2:\3:\4:\5:\6:\7/g' <<< "$LINE")
+		read IP MAC <<< "$IP_MAC"
+		IP_PADDED=$(printf "%15s" "$IP")
+		VENDOR=$(findVendor $MAC)
+		echo "$MAC $IP_PADDED  $VENDOR"
+
+	done < <(. cisco_command ${NODE} sh arp :: sh ip dhcp bind | grep -P '   ([0-9a-f]{3})?[0-9a-f.]{14} ' | perl -pe 's/(?:^|.*\D)([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) .*(([0-9a-f]{2})([0-9a-f]{2})\.([0-9a-f]{2})([0-9a-f]{2})\.([0-9a-f]{2})([0-9a-f]{2})|([0-9a-f]{2})\.([0-9a-f]{2})([0-9a-f]{2})\.([0-9a-f]{2})([0-9a-f]{2})\.([0-9a-f]{2})) .*/$1 $3:$4:$5:$6:$7:$8$9:$10:$11:$12:$13:$14/g;s/:{5}//g') | sort -Vu
+	#done < <(snmpbulkwalk -c${SNMPCOMMUNITY} -v2c -OXsqn "$NODE" .1.3.6.1.2.1.3.1.1.2) | sort -V # This only works with the arp table. DHCP bindings on cisco ios are not available via SNMP
+}
+
 refreshDatabase
 
 source cisco_auth
+DATA="$(getData | grep -Pi "$SEARCH")"
 
-while IFS= read -r LINE; do
-	IP_MAC=$(sed -E 's/.*\.([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) "(..) (..) (..) (..) (..) (..) ?"/\1 \2:\3:\4:\5:\6:\7/g' <<< "$LINE")
-	read IP MAC <<< "$IP_MAC"
-	IP_PADDED=$(printf "%15s" "$IP")
-	VENDOR=$(findVendor $MAC)
-	echo "$MAC $IP_PADDED  $VENDOR" | colorize red "..:..:..:..:..:.." green "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"
-
-done < <(. cisco_command ${NODE} sh arp :: sh ip dhcp bind | grep -P '   ([0-9a-f]{3})?[0-9a-f.]{14} ' | perl -pe 's/(?:^|.*\D)([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) .*(([0-9a-f]{2})([0-9a-f]{2})\.([0-9a-f]{2})([0-9a-f]{2})\.([0-9a-f]{2})([0-9a-f]{2})|([0-9a-f]{2})\.([0-9a-f]{2})([0-9a-f]{2})\.([0-9a-f]{2})([0-9a-f]{2})\.([0-9a-f]{2})) .*/$1 $3:$4:$5:$6:$7:$8$9:$10:$11:$12:$13:$14/g;s/:{5}//g') | sort -Vu
-#done < <(snmpbulkwalk -c${SNMPCOMMUNITY} -v2c -OXsqn "$NODE" .1.3.6.1.2.1.3.1.1.2) | sort -V # This only works with the arp table. DHCP bindings on cisco ios are not available via SNMP
+if [ -z "$NOCOLOR" ]; then
+	echo "$DATA" | colorize red "..:..:..:..:..:.." green "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"
+else
+	echo "$DATA"
+fi
 
